theme: minima
title: 'To Be Human'
author: 'PiSquaredBySix'
description: 'A collection of my thoughts and ryhmes'
instagram_username: to_be_human_69420

minima:
  social links::
    instagram: to_be_human_69420
